import { StyleSheet } from "react-native";

import { theme } from "@/app/theme";

const sharedStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    height: "100%",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.lg,
  },
  compactContainer: {
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
  },
  keyboardAvoidingContainer: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
  },
  innerContainer: {
    width: "100%",
    maxWidth: theme.layout.maxFormWidth,
    marginVertical: theme.spacing.md,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: theme.radii.xxl,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderBottomColor: theme.colors.primary,
    borderBottomWidth: 3,
    alignSelf: "center",
  },
  compactInnerContainer: {
    paddingHorizontal: 14,
    paddingVertical: theme.spacing.lg,
    borderRadius: theme.radii.xl,
    marginVertical: theme.spacing.sm,
  },
  title: {
    fontSize: theme.typography.fontSize.title1,
    fontWeight: "bold",
    marginBottom: 14,
    color: theme.colors.primary,
    letterSpacing: 0.5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  compactTitle: {
    fontSize: theme.typography.fontSize.title2,
    marginBottom: 10,
  },
  label: {
    alignSelf: "flex-start",
    fontSize: theme.typography.fontSize.body,
    fontWeight: "600",
    marginBottom: 6,
    color: theme.colors.primary,
  },
  compactLabel: {
    fontSize: theme.typography.fontSize.subhead,
    marginBottom: theme.spacing.xs,
  },
  errorMessage: {
    width: "100%",
    textAlign: "center",
    fontSize: theme.typography.fontSize.subhead,
    marginBottom: 10,
    minHeight: 20,
    color: theme.colors.danger,
    fontWeight: "600",
  },
  compactErrorMessage: {
    fontSize: theme.typography.fontSize.footnote,
    marginBottom: theme.spacing.sm,
    minHeight: 18,
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  button: {
    width: "100%",
    backgroundColor: theme.colors.surface,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.radii.md,
    marginTop: theme.spacing.sm,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderColor: theme.colors.primary,
    borderWidth: 1,
  },
  compactButton: {
    paddingVertical: 10,
    marginTop: 6,
  },
  buttonText: {
    color: theme.colors.primary,
    fontSize: theme.typography.fontSize.body,
    fontWeight: "bold",
    textAlign: "center",
  },
  compactButtonText: {
    fontSize: theme.typography.fontSize.subhead,
  },
  buttonNext: {
    width: "100%",
    backgroundColor: theme.colors.surface,
    paddingVertical: 10,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radii.md,
    marginTop: 14,
    marginBottom: 6,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderColor: theme.colors.borderStrong,
    borderWidth: 1,
  },
  compactButtonNext: {
    paddingVertical: theme.spacing.sm,
    marginTop: 10,
    marginBottom: theme.spacing.xs,
  },
  greyText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.fontSize.footnote,
    fontWeight: "400",
  },
  compactGreyText: {
    fontSize: theme.typography.fontSize.caption,
  },
  containerFooter: {
    textAlign: "center",
    color: theme.colors.textMuted,
    marginTop: theme.spacing.lg,
    paddingTop: 10,
    fontSize: theme.typography.fontSize.subhead,
    lineHeight: 20,
    borderTopWidth: 1,
    borderColor: theme.colors.borderStrong,
    width: "100%",
  },
  compactContainerFooter: {
    marginTop: theme.spacing.md,
    paddingTop: theme.spacing.sm,
    fontSize: theme.typography.fontSize.footnote,
    lineHeight: 18,
  },
  footerLink: {
    color: theme.colors.primary,
    fontWeight: "bold",
  },
});

export default sharedStyles;
