
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  loki:
    user: '0'
    image: grafana/loki:2.9.1
    ports:
      - '3100:3100'
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki-data/wal:/wal
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/cache:/loki/cache
      - ./loki-data/compactor:/loki/compactor
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3100/ready || exit 1"]
      interval: 90s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ../backend/app.log:/app/backend/app.log:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local