"""Add status column to Post

Revision ID: e8cb5b3a6892
Revises: 0b92d645586b
Create Date: 2025-07-13 16:04:26.494753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cb5b3a6892'
down_revision: Union[str, None] = '0b92d645586b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderation_log', 'status')
    op.add_column('post', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status')
    op.add_column('moderation_log', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
