

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:latest
    restart: unless-stopped
    container_name: keycloak_server
    ports:
      - "${PORT_KEYCLOAK}:8080"
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRESQL_DB}
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
      KC_HOSTNAME: auth.yeslove.co.uk
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KC_HOSTNAME_URL: https://auth.yeslove.co.uk
      KC_HOSTNAME_ADMIN_URL: https://auth.yeslove.co.uk
      KC_PROXY_HEADERS: xforwarded

    env_file:
      - .env
    command: start-dev --import-realm --hostname-strict=false
    depends_on:
      - postgres

volumes:
  postgres_data:
