"""Add notification settings table

Revision ID: 4893553cb2e3
Revises: 5593202cc71c
Create Date: 2025-09-27 18:59:20.155242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4893553cb2e3'
down_revision = '5593202cc71c'
branch_labels = None
depends_on = None


def _has_table(table_name):
    bind = op.get_bind()
    return sa.inspect(bind).has_table(table_name)


def _has_column(table_name, column_name):
    bind = op.get_bind()
    if not sa.inspect(bind).has_table(table_name):
        return False
    columns = sa.inspect(bind).get_columns(table_name)
    return any(column["name"] == column_name for column in columns)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('address'):
        op.create_table('address',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.String(length=100), nullable=False),
        sa.Column('street', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=False),
        sa.Column('county', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('post_code', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table('event'):
        op.create_table('event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('location', sa.String(length=100), nullable=False),
        sa.Column('event_time', sa.DateTime(), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('address_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table('notification_settings'):
        op.create_table('notification_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('posts_enabled', sa.Boolean(), nullable=True),
        sa.Column('likes_enabled', sa.Boolean(), nullable=True),
        sa.Column('comments_enabled', sa.Boolean(), nullable=True),
        sa.Column('events_enabled', sa.Boolean(), nullable=True),
        sa.Column('blogs_enabled', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_table('attendees'):
        op.create_table('attendees',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'event_id')
        )
    if not _has_column('blog_posts', 'summary'):
        with op.batch_alter_table('blog_posts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('summary', sa.String(length=1000), nullable=True))

    if not _has_column('chat', 'opened'):
        with op.batch_alter_table('chat', schema=None) as batch_op:
            batch_op.add_column(sa.Column('opened', sa.Boolean(), nullable=True))

    if not _has_column('follow', 'follow_type'):
        with op.batch_alter_table('follow', schema=None) as batch_op:
            batch_op.add_column(sa.Column('follow_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_column('follow_type')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('opened')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('summary')

    op.drop_table('attendees')
    op.drop_table('notification_settings')
    op.drop_table('media')
    op.drop_table('event')
    op.drop_table('documents')
    op.drop_table('address')
    # ### end Alembic commands ###
