"""Reinitializing migrations

Revision ID: 4c8438887999
Revises: b47651c9a285
Create Date: 2025-02-27 15:39:05.391970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8438887999'
down_revision = 'b47651c9a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('is_professional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_professional', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
