"""Added settings tables for email notifications and profile visibility

Revision ID: 6e5305e2dce2
Revises: 4c8438887999
Create Date: 2025-03-01 00:23:11.492207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5305e2dce2'
down_revision = '4c8438887999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('setting_id', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.keycloak_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_visibility_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('setting_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.keycloak_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_visibility_settings')
    op.drop_table('email_notification_settings')
    # ### end Alembic commands ###
