"""empty message

Revision ID: 797c143dcaa8
Revises: 824f71d28dd7
Create Date: 2025-11-02 15:04:45.100908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797c143dcaa8'
down_revision = '824f71d28dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        #batch_op.drop_constraint('attendees_user_id_fkey', type_='foreignkey')
        #batch_op.drop_constraint('attendees_event_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_attendees_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_attendees_event_id', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_attendees_media_id', 'media', ['media_id'], ['id'])

    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_device_token_token', ['token'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        #batch_op.drop_constraint('event_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_event_creator_id', 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_media_id', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
