"""Initial migration

Revision ID: f69d5bc533b6
Revises: d492599e6d25
Create Date: 2025-06-28 16:42:42.362091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69d5bc533b6'
down_revision = 'd492599e6d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_body', sa.String(length=20), nullable=True, comment='HCPC, BACP or UKCP'))
        batch_op.add_column(sa.Column('license_number', sa.String(length=100), nullable=True, comment='Professional license/registration number'))
        batch_op.add_column(sa.Column('consent_license_data', sa.Boolean(), nullable=False, comment='User consented to use and display license data'))
        batch_op.drop_column('license')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False, comment="User's country"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')

    with op.batch_alter_table('professional_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('consent_license_data')
        batch_op.drop_column('license_number')
        batch_op.drop_column('license_body')

    # ### end Alembic commands ###
