import theme from "@/assets/variables/Variables";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
  },
  profileImageContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  profileBackgroundImage: {
    width: theme.spacing.postWidth,
    minHeight: 250,
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "center",
    borderRadius: 18,
    overflow: "hidden",
    paddingVertical: 18,
    paddingHorizontal: 14,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 6,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 18, 45, 0.45)',
    borderRadius: 18
  },
  profileImage: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 3,
    borderStyle: "solid",
    borderColor: "#fff"
  },
  profileImageWrapper: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  changePhotoBadge: {
    position: 'absolute',
    bottom: -12,
    alignSelf: 'center',
    backgroundColor: theme.colors.primaryBlue,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#fff',
  },
  changePhotoBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  previewActionsContainer: {
    width: '88%',
    marginTop: 4,
    alignItems: 'center',
  },
  previewMessage: {
    color: '#fff',
    fontSize: 12,
    marginBottom: 7,
    textAlign: 'center',
  },
  previewButtonsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  previewButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    paddingVertical: 8,
  },
  previewButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  cancelButton: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: theme.colors.primaryBlue,
  },
  cancelButtonText: {
    color: theme.colors.primaryBlue,
  },
  uploadButton: {
    backgroundColor: theme.colors.primaryBlue,
  },
  disabledButton: {
    opacity: 0.6,
  },
  validationMessage: {
    marginTop: 6,
    color: '#ffb4b4',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    width: '90%',
  },
  successMessage: {
    marginTop: 6,
    color: '#d0ffd7',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    width: '90%',
  },
  userName: {
   color: "#fff",
   fontSize: 21,
   fontWeight: '700',
   letterSpacing: 0.2,
   textAlign: "center",
  },
  userStatsContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 2,
  },
  userStats: {
    color: "#e5e7eb",
    fontSize: 12,
    marginLeft: 0,
    marginRight: 0,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    overflow: "hidden",
  },
  userStatsNumber: {
    fontWeight: '700',
    color: "#fff",
  },
  userBioContainer:{
    width: "100%",
    minHeight: 78,
    marginTop: 12,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 7,
    elevation: 3,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  userBioText: {
    color: "#111827",
    fontSize: 13,
    lineHeight: 19,
  },
  emptyBioTitle: {
    color: "#1f2937",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 3,
  },
  emptyBioText: {
    color: "#4b5563",
    fontSize: 12,
    lineHeight: 17,
  },
})

export default styles